name: |-
  Features Branch (Pull Request) Workflow 
  
  ### Usage 
  
  In your repo create  __`.github/workflows/feature-branch.yaml`__
  
  ```yaml
    name: Feature Branch
    on:
      pull_request:
        branches: [ main ]
        types: [opened, synchronize, reopened]
    
    permissions:
      pull-requests: write
      id-token: write
      contents: read
    
    jobs:
      default:
        uses: cloudposse/github-actions-workflows-terraform-module/.github/workflows/feature-branch.yml@main

  ```

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci_terraform:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-terraform.yml@shared_worflows
    with:
      # Workaround for https://github.com/community/community/discussions/9099
      # We should switch to nofilter once it's fixed
      filter_mode: diff_context
      suggestions: true

  ci_readme:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-readme.yml@shared_worflows
    with:
      # Workaround for https://github.com/community/community/discussions/9099
      # We should switch to nofilter once it's fixed
      filter_mode: diff_context
      suggestions: true
