name: |-
  Features branch (Pull request) workflow 
  
  Build, test Docker image, deploy it to EKS `preview` environment depends of PR labels  
  
  ### Usage 
  
  Create in your repo  __`.github/workflows/feature.yaml`__
  
  ```yaml
    name: Feature Branch
    on:
      pull_request:
        branches: [ 'master' ]
        types: [opened, synchronize, reopened, closed, labeled, unlabeled]
    
    permissions:
      pull-requests: write
      deployments: write
      id-token: write
      contents: read
    
    jobs:
      do:
        uses: cloudposse/github-actions-workflows-docker-ecr-eks-helmfile/.github/workflows/feature-branch.yml@main
        with:
          organization: "$\{\{ github.event.repository.owner.login \}\}"
          repository: "$\{\{ github.event.repository.name \}\}"
          open: $\{\{ github.event.pull_request.state == 'open' \}\}
          labels: $\{\{ toJSON(github.event.pull_request.labels.*.name) \}\}
          ref: $\{\{ github.event.pull_request.head.ref  \}\}
        secrets:
          github-private-actions-pat: "$\{\{ secrets.PUBLIC_REPO_ACCESS_TOKEN \}\}"
          registry: "$\{\{ secrets.ECR_REGISTRY \}\}"
          secret-outputs-passphrase: "$\{\{ secrets.GHA_SECRET_OUTPUT_PASSPHRASE \}\}"
          ecr-region: "$\{\{ secrets.ECR_REGION \}\}"
          ecr-iam-role: "$\{\{ secrets.ECR_IAM_ROLE \}\}"
  ```

on:
  workflow_call:
    inputs:
      organization:
        description: "Repository owner organization (ex. acme for repo acme/example)"
        required: false
        default: ${{ github.event.repository.owner.login }}
        type: string
      repository:
        description: "Repository name (ex. example for repo acme/example)"
        required: false
        default: ${{ github.event.repository.name }}
        type: string
      ref:
        description: "The fully-formed ref of the branch or tag that triggered the workflow run"
        required: false
        default: ${{ github.event.pull_request.head.ref }}
        type: string
      open:
        description: "Pull Request open/close state. Set true if opened"
        required: false
        type: boolean
        default: ${{ github.event.pull_request.state == 'open' }}

permissions:
  pull-requests: read
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ci/terraform:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-terraform.yml@main
    with:
      organization: ${{ inputs.organization }}
      repository: ${{ inputs.repository }}
      suggestions: true

  ci/readme:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-readme.yml@main
    with:
      organization: ${{ inputs.organization }}
      repository: ${{ inputs.repository }}
      suggestions: true

  comment:
    needs: [ci/terraform, ci/readme]
    uses: cloudposse/github-actions-workflows/.github/workflows/controller-comment-pr.yml@main
    with:
      organization: ${{ inputs.organization }}
      repository: ${{ inputs.repository }}
      comment: "Reach us in SweetOps channel to get review"