name: |-
  Features Branch (Pull Request) Workflow 
  
  ### Usage 
  
  In your repo create  __`.github/workflows/feature-branch.yaml`__
  
  ```yaml
    name: Feature Branch
    on:
      pull_request:
        branches: [ main ]
        types: [opened, synchronize, reopened, closed, labeled, unlabeled]
    
    permissions:
      pull-requests: read
      id-token: write
      contents: read
    
    jobs:
      default:
        uses: cloudposse/github-actions-workflows-terraform-module/.github/workflows/feature-branch.yml@main

  ```

on:
  workflow_call:

permissions:
  pull-requests: read
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ci/terraform:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-terraform.yml@shared_worflows
    with:
      suggestions: true

  ci/readme:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-readme.yml@shared_worflows
    with:
      suggestions: true
