name: |-
  Main Branch Workflow
  
  ### Usage 
  
  In your repo create  __`.github/workflows/main-branch.yaml`__
  
  ```yaml
    name: Main Branch
    on:
      push:
        branches: [ main ]
    
    permissions:
      contents: write
      id-token: write
    
    jobs:
      default:
        uses: cloudposse/github-actions-workflows-terraform-module/.github/workflows/main-branch.yml@main

  ```

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ci_terraform:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-terraform.yml@shared_worflows
    with:
      filter_mode: nofilter
      suggestions: false

  ci_readme:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-readme.yml@shared_worflows
    with:
      filter_mode: nofilter
      suggestions: false

  controller_release:
    uses: cloudposse/github-actions-workflows/.github/workflows/controller-release.yml@shared_worflows
    needs: [ci_terraform, ci_readme]