name: |-
  Main Branch Workflow
  
  ### Usage 
  
  In your repo create  __`.github/workflows/main-branch.yaml`__
  
  ```yaml
    name: Main Branch
    on:
      push:
        branches: [ main ]
    
    permissions:
      contents: write
      id-token: write
    
    jobs:
      terraform-module:
        uses: cloudposse/github-actions-workflows-terraform-module/.github/workflows/feature-branch.yml@main
        secrets:
          github_access_token: $\{\{ secrets.GH_ACCESS_TOKEN \}\}
  ```

on:
  workflow_call:
    secrets:
      github_access_token:
        description: "GitHub API token"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ci_terraform:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-terraform.yml@main
    with:
      filter-mode: nofilter
      suggestions: false

  ci_readme:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-readme.yml@main
    with:
      filter-mode: nofilter
      suggestions: false

  ci_codeowners:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-codeowners.yml@main
    with:
      is_fork: false
    secrets:
      github_access_token: ${{ secrets.github_access_token }}

  controller_release:
    uses: cloudposse/github-actions-workflows/.github/workflows/controller-release.yml@main
    needs: [ci_terraform, ci_readme, ci_codeowners]